$text = rgb({{colors.on_background.default.hex_stripped}})
$textAlpha55 = {{colors.on_background.default.hex_alpha | to_color | set_alpha: 0.55 | format: "hex_alpha_stripped"}}
$red = rgb({{colors.error.default.hex_stripped}})
$green = rgb({{colors.tertiary.default.hex_stripped}})
$blue = rgb({{colors.secondary.default.hex_stripped}})
