$background = rgb(111318)
$onBackground = rgb(e2e2e9)

$primary = rgb(adc6ff)
$onPrimary = rgb(102f60)
$primaryContainer = rgb(2b4678)
$onPrimaryContainer = rgb(d8e2ff)

$secondary = rgb(bfc6dc)
$onSecondary = rgb(293041)
$secondaryContainer = rgb(3f4759)
$onSecondaryContainer = rgb(dbe2f9)

$tertiary = rgb(debcdf)
$onTertiary = rgb(402843)
$tertiaryContainer = rgb(583e5b)
$onTertiaryContainer = rgb(fbd7fc)

$error = rgb(ffb4ab)
$onError = rgb(690005)
$errorContainer = rgb(93000a)
$onErrorContainer = rgb(ffdad6)

$surface = rgb(111318)
$onSurface = rgb(e2e2e9)
$surfaceVariant = rgb(44474f)
$onSurfaceVariant = rgb(c4c6d0)
$surfaceContainer = rgb(1e1f25)
$surfaceContainerLow = rgb(1a1b20)
$surfaceContainerHigh = rgb(282a2f)

$outline = rgb(8e9099)
$outlineVariant = rgb(44474f)
