-- Hyprland Lua config, converted from hyprland.conf
-- Reference: https://wiki.hypr.land/0.56.0/Configuring/Start/


-----------------
---- COLORS -----
-----------------

-- Generated by matugen (template "hyprland_lua" -> ~/.config/hypr/colors.lua).
-- pcall so a missing colors file doesn't abort the whole config
-- (see "Require" on the Start wiki page).
local ok, colors = pcall(require, "colors")
if not ok then
  colors = { primary = "rgb(1E3F33)" }
end


------------------
---- MONITORS ----
------------------

hl.monitor({
  output   = "",
  mode     = "highres",
  position = "auto-left",
  scale    = 1,
})


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

hl.env("XCURSOR_THEME", "")
hl.env("XCURSOR_SIZE", "16")
hl.env("HYPRCURSOR_THEME", "")
hl.env("HYPRCURSOR_SIZE", "16")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")


---------------------
---- MY PROGRAMS ----
---------------------

local terminal    = "kitty"
local fileManager = "nautilus"
local menu        = "rofi -show drun"
local browser     = "firefox"


-------------------
---- AUTOSTART ----
-------------------

hl.on("hyprland.start", function()
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme \"prefer-dark\"")
  hl.exec_cmd("awww-daemon & sleep 0.5 && awww clear")
  hl.exec_cmd("wl-paste --type text --watch cliphist store")
  hl.exec_cmd("wl-paste --type image --watch cliphist store")
  hl.exec_cmd("bash ~/.config/scripts/media.sh")
  hl.exec_cmd("waybar")
  hl.exec_cmd("fcitx5 -d")
end)


-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
  general = {
    gaps_in     = 5,  -- @dynamic_gaps_in
    gaps_out    = 10, -- @dynamic_gaps_out
    border_size = 2,  -- @dynamic_border

    col = {
      active_border = colors.primary,
    },

    resize_on_border = false,
    allow_tearing    = false,

    layout = "dwindle",
  },

  decoration = {
    rounding       = 0,
    rounding_power = 0,

    active_opacity   = 1.0,
    inactive_opacity = 1.0,

    shadow = {
      enabled      = true,
      range        = 4,
      render_power = 3,
      color        = "rgba(1a1a1aee)",
    },

    blur = {
      enabled  = true,
      size     = 3,
      passes   = 1,
      vibrancy = 0.1696,
    },
  },

  animations = {
    enabled = true,
  },

  dwindle = {
    preserve_split = true,
  },

  misc = {
    force_default_wallpaper    = 0,
    disable_hyprland_logo      = true,
    disable_splash_rendering   = true,
    initial_workspace_tracking = 1,
  },
})


--------------------
---- ANIMATIONS ----
--------------------

hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}   } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}   } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}      } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}   } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}    } })
hl.curve("hard",           { type = "bezier", points = { {0, 1},       {0, 1}      } })

hl.animation({ leaf = "global",           enabled = true, speed = 5,    bezier = "default" })
hl.animation({ leaf = "border",           enabled = true, speed = 2.5,  bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",          enabled = true, speed = 2.5,  bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn",        enabled = true, speed = 2,    bezier = "easeOutQuint", style = "popin 87%" })
hl.animation({ leaf = "windowsOut",       enabled = true, speed = 1,    bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",           enabled = true, speed = 1,    bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",          enabled = true, speed = 1,    bezier = "almostLinear" })
hl.animation({ leaf = "fade",             enabled = true, speed = 1.5,  bezier = "quick" })
hl.animation({ leaf = "layers",           enabled = true, speed = 2,    bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",         enabled = true, speed = 2,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",        enabled = true, speed = 1,    bezier = "linear",       style = "fade" })
hl.animation({ leaf = "workspaces",       enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" }) -- @dynamic_workspaces
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" }) -- @dynamic_special


----------------------
---- INPUT ----------
----------------------

hl.config({
  input = {
    kb_layout = "us",

    follow_mouse = 1,

    sensitivity        = 0,
    force_no_accel     = false,
    numlock_by_default = true,

    touchpad = {
      natural_scroll = false,
    },
  },
})


----------------------
---- WINDOW RULES ----
----------------------

hl.window_rule({
  name   = "floating-window-tag",
  match  = { tag = "floating-window" },
  float  = true,
  center = true,
  size   = { 800, 600 },
})

-- File pickers / save dialogs get the floating-window tag
hl.window_rule({
  name  = "tag-file-dialogs",
  match = {
    class = "^(local\\.xdg-desktop-portal-gtk|local\\.sublime_text|local\\.DesktopEditors|local\\.org\\.gnome\\.Nautilus)$",
    title = "^(Open.*Files?|Open [Ff]older.*|Save.*Files?|Save.*As|Save|All Files)$",
  },
  tag   = "+floating-window",
})

-- CLI tools
hl.window_rule({
  name   = "cli-tools-float",
  match  = { class = "^(local\\.bluetui|local\\.impala|local\\.wiremix|local\\.org\\.gnome\\.NautilusPreviewer|local\\.com\\.gabm\\.satty)$" },
  float  = true,
  center = true,
  size   = { 800, 600 },
})

-- Floating generic class
hl.window_rule({
  name   = "generic-float",
  match  = { class = "^(local\\.floating)$" },
  float  = true,
  center = true,
  size   = { 800, 600 },
})

hl.window_rule({
  name   = "mv",
  match  = { initial_class = "^(imv|mpv|wiremix|impala)$" },
  float  = true,
  center = true,
  size   = { 600, 600 },
})

-- jetbrains
-- hl.window_rule({
--   name     = "jetbrains_float_has_min_size",
--   match    = { class = "^(jetbrains-.*)$", title = "^$", float = true },
--   min_size = { 800, 600 },
-- })
-- hl.window_rule({ match = { class = "jetbrains-.*", title = "splash", float = true }, center = true })
-- hl.window_rule({ match = { class = "jetbrains-.*", title = "splash", float = true }, no_focus = true })
-- hl.window_rule({ match = { class = "jetbrains-.*", title = "win.*",  float = true }, no_focus = true })
-- hl.window_rule({ match = { class = "jetbrains-.*", float = true }, no_blur = true })
-- hl.window_rule({ match = { class = "jetbrains-.*", float = true }, no_initial_focus = true })
-- hl.window_rule({ match = { class = "jetbrains-.*", float = true }, opacity = "1 override 1 override 1 override" })

-- "Smart gaps" -- @dynamic_smartgaps
-- hl.workspace_rule({ workspace = "w[t1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",  gaps_out = 0, gaps_in = 0 })


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER"

hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + W", hl.dsp.window.close())
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd("~/.config/scripts/master.sh"))
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("~/.config/scripts/power.sh"))
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("~/.config/scripts/time.sh"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("cliphist list | rofi -dmenu | cliphist decode | wl-copy"))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen" }))
hl.bind(mainMod .. " + Tab", hl.dsp.focus({ workspace = "m+1" }))
hl.bind(mainMod .. " + P", hl.dsp.exec_cmd("hyprpicker --autocopy"))
hl.bind("SHIFT + ALT + S", hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | wl-copy"))

hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("brightnessctl set +5%"))
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"))

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Move window with SHIFT + arrow keys
hl.bind("SHIFT + left",  hl.dsp.window.move({ direction = "left" }))
hl.bind("SHIFT + right", hl.dsp.window.move({ direction = "right" }))
hl.bind("SHIFT + up",    hl.dsp.window.move({ direction = "up" }))
hl.bind("SHIFT + down",  hl.dsp.window.move({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
  local key = i % 10 -- 10 maps to key 0
  hl.bind(mainMod .. " + " .. key,         hl.dsp.focus({ workspace = i }))
  hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Special workspace (scratchpad)
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })
