# The kitty terminal template for wallust
# Add to wallust config: kitty = { src='kitty.conf', dst='~/.config/kitty/colors.conf'}
# And add to kitty config: include colors.conf

cursor #88A1AE

background #03040A
foreground #AFCCD7

color0 #04060C
color1 #343A48
color2 #444F5F
color3 #51606F
color4 #576C86
color5 #617684
color6 #6D8892
color7 #9FBBC6
color8 #637E88
color9 #343A48
color10 #444F5F
color11 #51606F
color12 #576C86
color13 #617684
color14 #6D8892
color15 #C6D5DA

mark1_foreground #578292
mark2_foreground #7FB2C6
mark3_foreground #578292

